from Agent import Agent
from Annotation import Annotation
from Catalog import Catalog
from CatalogRecord import CatalogRecord
from Checksum import Checksum
from Concept import Concept
from ConceptScheme import ConceptScheme
from ContactPoint import ContactPoint
from CreativeWork import CreativeWork
from Document import Document
from EPOSWebService import EPOSWebService
from Equipment import Equipment
from Facility import Facility
from Frequency import Frequency
from HydraAPIDocumentation import HydraAPIDocumentation
from HydraClass import HydraClass
from HydraIriTemplate import HydraIriTemplate
from HydraIriTemplateMapping import HydraIriTemplateMapping
from HydraOperation import HydraOperation
from Identifier import Identifier
from Kind import Kind
from LicenseDocument import LicenseDocument
from LinguisticSystem import LinguisticSystem
from Location import Location
from MediaTypeOrExtent import MediaTypeOrExtent
from Organization import Organization
from PeriodOfTime import PeriodOfTime
from Person import Person
from PostalAddress import PostalAddress
from Project import Project
from PropertyValue import PropertyValue
from ProvenanceStatement import ProvenanceStatement
from Publication import Publication
from RDFSLiteral import RDFSLiteral
from Resource import Resource
from RightsStatement import RightsStatement
from Service import Service
from SoftwareApplication import SoftwareApplication
from SoftwareSourceCode import SoftwareSourceCode
from Standard import Standard
