from Annotation import Annotation
from Concept import Concept
from ConceptScheme import ConceptScheme
from ContactPoint import ContactPoint
from CreativeWork import CreativeWork
from EPOSWebService import EPOSWebService
from Equipment import Equipment
from HydraAPIDocumentation import HydraAPIDocumentation
from HydraClass import HydraClass
from HydraIriTemplate import HydraIriTemplate
from HydraIriTemplateMapping import HydraIriTemplateMapping
from HydraOperation import HydraOperation
from Facility import Facility
from Organization import Organization
from Person import Person
from PostalAddress import PostalAddress
from Project import Project
from PropertyValue import PropertyValue
from Publication import Publication
from Service import Service
from SoftwareApplication import SoftwareApplication
from SoftwareSourceCode import SoftwareSourceCode
